runtime: python312 
# Substitua "SEUPROJETO" pelo nome do seu projeto Django (o mesmo nome da pasta que tem o arquivo settings.py)
# O restante é para usar mais threads em um mesmo servidor
entrypoint: gunicorn -b :$PORT pw2026.wsgi --workers 1 --threads 6 --worker-class gthread

# Criar variáveis de ambiente no app engine
env_variables:
  NOMEDAVARIAVEL: "Valor dela"
  VARIAVEL_API: "abc-1234"

handlers:
- url: /static
  static_dir: static_gcloud/
- url: /.*
  script: auto

automatic_scaling:
  min_instances: 0
  max_instances: 2
