# Generated by Django 5.1 on 2026-04-16 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name="campeonato",
            name="campus",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="website.campus",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jogador",
            name="campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="website.campus"
            ),
        ),
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_time",
                    models.CharField(
                        help_text="Informe o nome do time, ex: Time Alpha",
                        max_length=60,
                        verbose_name="Nome do time",
                    ),
                ),
                ("confirmada", models.BooleanField(default=False)),
                ("confirmada_em", models.DateTimeField(blank=True, null=True)),
                ("inscrito_em", models.DateTimeField(auto_now_add=True)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="website.campeonato",
                    ),
                ),
                (
                    "inscrito_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("jogadores", models.ManyToManyField(to="website.jogador")),
                (
                    "modalidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="website.modalidade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        blank=True,
                        help_text="Informe a data e hora do jogo, ex: 2024-12-31 18:00",
                        null=True,
                        verbose_name="data e hora do jogo",
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        blank=True,
                        help_text="Informe o resultado do jogo, ex: 2-1",
                        max_length=30,
                        null=True,
                        verbose_name="resultado do jogo",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="website.fase"
                    ),
                ),
                (
                    "modalidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="website.modalidade",
                    ),
                ),
                (
                    "time_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_1",
                        to="website.inscricao",
                    ),
                ),
                (
                    "time_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_2",
                        to="website.inscricao",
                    ),
                ),
                (
                    "vencedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vencedor",
                        to="website.inscricao",
                    ),
                ),
            ],
        ),
    ]
