# Generated by Django 5.2.13 on 2026-06-18 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_campus_campeonato_campus_alter_jogador_campus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(blank=True, default='', max_length=14)),
                ('telefone', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('capacidade', models.PositiveSmallIntegerField()),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor da diária')),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='campeonato',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='inscrito_por',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='jogadores',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='time_2',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='vencedor',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='time_1',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='modalidade',
        ),
        migrations.RenameModel(
            old_name='Modalidade',
            new_name='StatusReserva',
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateTimeField(verbose_name='data de check-in')),
                ('data_checkout', models.DateTimeField(verbose_name='data de check-out')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor total')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.hospede')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.quarto')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.statusreserva')),
            ],
        ),
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(blank=True, help_text='Informe a data de entrada, ex: 2024-12-31 14:00', null=True, verbose_name='data de entrada')),
                ('data_saida', models.DateTimeField(blank=True, help_text='Informe a data de saída, ex: 2025-01-01 11:00', null=True, verbose_name='data de saída')),
                ('finalizada', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='quarto',
            name='tipo_quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.tipoquarto'),
        ),
        migrations.DeleteModel(
            name='Campeonato',
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='Fase',
        ),
        migrations.DeleteModel(
            name='Inscricao',
        ),
        migrations.DeleteModel(
            name='Jogador',
        ),
        migrations.DeleteModel(
            name='Jogo',
        ),
    ]
