# Generated by Django 5.2.13 on 2026-06-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_hospede_quarto_tipoquarto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedagem',
            name='data_entrada',
            field=models.DateField(blank=True, help_text='Informe a data de entrada, ex: 2024-12-31', null=True, verbose_name='data de entrada'),
        ),
        migrations.AlterField(
            model_name='hospedagem',
            name='data_saida',
            field=models.DateField(blank=True, help_text='Informe a data de saída, ex: 2025-01-01', null=True, verbose_name='data de saída'),
        ),
    ]
